import { DEFAULT_PRODUCT_PALETTE_ID } from "../../config/productPalettes.js";

const today = () => new Date().toISOString().slice(0, 10);

export const createProductDefaults = () => ({
  id: "",
  slug: "",
  name: "",
  summary: "",
  description: "",
  image: "",
  imageAlt: "",
  categorySlug: "",
  collectionSlugs: [],
  recommendationReason: "",
  pros: [],
  considerations: [],
  suitableFor: [],
  notSuitableFor: [],
  keywords: [],
  aliases: [],
  featured: false,
  newest: true,
  sortOrder: 999,
  status: "draft",
  demo: false,
  updatedAt: today(),
  reviewedAt: "",
  imageSource: "",
  imageLicense: "",
  imageWidth: 0,
  imageHeight: 0,
  marketplaceProductId: "",
  affiliateDisclosureVariant: "default",
  affiliateLinks: [],
  contentReferences: [],
  visual: {
    paletteId: DEFAULT_PRODUCT_PALETTE_ID,
    imageFit: "contain",
    imageScale: "medium",
    imagePosition: "center",
  },
});
